// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:bd2d67d3-1680-4d34-af49-267d0b34bbd4",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_n9VQZIETG",
    "aws_user_pools_web_client_id": "6d40glujconulk9sk3opad18bi"
};


export default awsmobile;
